experimenter: JohnDoe
prep_choices: [Behavior, Left optic lobe, Right optic lobe, Whole brain, Optic glomeruli]
driver_choices: [isoD1, Tm3 (R13E12-Gal4), Tm3 (R13E12-LexA), nSyb-Gal4, EG-Gal4]
indicator_choices: [TdTomato, GCaMP8f, GCaMP7f, GCaMP6f, GCaMP6m, Syt1GCaMP6f, SytGCaMP6S, Syt1GCaMP7FU, GCaMP6S.brpS.mCherry, ASAP2f, ASAP4c, ASAP4c_F413G, 10_90_GCaMP6f, 10_90_GCaMP7f, 10_90_ASAP2f, 10_90_ASAP4c, 10_90_ASAP4c_F413G, SF-iGluSnFR.A184V]
effector_choices: [Kir2.1, Shi, CsChrimson, GtACR]

rig_config:
  Bruker_LeftScreen:
    data_directory: E:/Minseung/FlystimData
    screen_center: [0,-30]
    rig: Bruker
    devices:
      daq:
        labjack

  Laptop:
    data_directory: /Volumes/GoogleDrive/My\ Drive/research/clandinin_lab/data/FlystimData
    screen_center: [0, 0]
    rig: (testing)
    devices:
      daq: 

protocol_module_path: lab_package/user/JohnDoe_protocol.py
data_module_path: lab_package/lab/lab_data.py
client_module_path: lab_package/lab/lab_client.py
parameter_presets_dir: lab_package/user/presets/JohnDoe

